### ISSUE TITLE
官网出bug了

### ISSUE THREAD

**Issue by CoderOrangesoft** [codemaoTeam/codemao-api#11]
鼠标滚轮在标题栏滑的了，但是在内容栏不论怎么划都划不了

**Comment by CoderOrangesoft** [comment]
![image](https://user-images.githubusercontent.com/104307711/231997325-23bc911e-799b-4b79-ac95-063a8be24315.png)
具体见图

**Comment by lambdark** [comment]
应该好了吧，我也不知道怎么出的bug，没修过又自己好了
